### ISSUE TITLE
Server pack 1.8.7 broken

### ISSUE THREAD

**Issue by aft2d** [Flairieve/Massive-Dig#1]
It looks like the server pack for 1.8.7 is broken in multiple ways:
1) libraries
The libraries folder seems to be corrupt or not correctly installed:
After unpacking the server zip file and starting the server you'll get this error:
`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
`
I fixed this by deleting the libraries folder and rerunning the forge installer.

2) Missing mods
It looks like the server is missing mods/dependencies in order to run;
`[DBG] [SERVER] [15:10:48] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod extracells (Extra Cells 2) requires [appliedenergistics2]
[DBG] [SERVER] [15:10:48] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod mekanismgenerators (Mekanism: Generators) requires [mekanism@[1.12.2-9.7.3.374,1.12.2-9.7.3.374]]
[DBG] [SERVER] [15:10:48] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod mekanismtools (Mekanism: Tools) requires [mekanism@[1.12.2-9.7.3.374,1.12.2-9.7.3.374]]
[DBG] [SERVER] [15:10:48] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod plustic (PlusTiC) requires [tconstruct@[1.12-2.7.2.15,)]
[DBG] [SERVER] [15:10:48] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod tinkertoolleveling (Tinkers Tool Leveling) requires [tconstruct@[1.12-2.10,)]
[DBG] [SERVER] [15:10:48] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
[DBG] [SERVER] net.minecraftforge.fml.common.MultipleModsErrored: 
[DBG] [SERVER] Missing Mods:
[DBG] [SERVER] 	unknown : need any: have missing
[DBG] [SERVER] 
[DBG] [SERVER] Missing Mods:
[DBG] [SERVER] 	unknown : need [1.12.2-9.7.3.374,1.12.2-9.7.3.374]: have missing
[DBG] [SERVER] 
[DBG] [SERVER] Missing Mods:
[DBG] [SERVER] 	unknown : need [1.12.2-9.7.3.374,1.12.2-9.7.3.374]: have missing
[DBG] [SERVER] 
[DBG] [SERVER] Missing Mods:
[DBG] [SERVER] 	unknown : need [1.12-2.7.2.15,): have missing
[DBG] [SERVER] 
[DBG] [SERVER] Missing Mods:
[DBG] [SERVER] 	unknown : need [1.12-2.10,): have missing
[DBG] [SERVER] 
[DBG] [SERVER] 
`

**Comment by Flairieve** [comment]
Huh that's strange? It needs a newer version of tinker's construct but it should have crashed on singleplayer also? Going to fix this quickly

**Comment by Flairieve** [comment]
I just tested out the server pack and the issues are not there and the server is running correctly. The only issue I see is the startServer.bat pointing to the wrong jar file. Try installing a newer version of Java and see if that fixes it.

**Comment by Flairieve** [comment]
I just uploaded a fix version of the server pack which points to the right jar file now so it should be working now.
